### ISSUE TITLE
plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [zho/phonegap-imeiplugin#2]
according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by zho** [comment]
done!

**Comment by bau720123** [comment]
hi @zho 
thanks your effort

but in this address
https://www.npmjs.com/package/imeiplugin
there is no any readme，is it normal ?

**Comment by zho** [comment]
well, i still dont know how to add readme file haha, about package name, i cannot change it :(

**Comment by bau720123** [comment]
hi @zho 
thanks for your reply
I am using PGB 5.1.1
when I install from pgb source
```
<gap:plugin name="com.joandilee.imeiplugin" source="pgb" version="0.1" />
```
all platform build success

but when I install this from npm
```
<gap:plugin name="imeiplugin " source="npm" version="1.0.1" />
```
it will Indirectly cause wp8 version build fail
I know this plugin have no wp8 version
but indeed...

**Comment by bau720123** [comment]
hi @zho 
any reply ?

**Comment by bau720123** [comment]
just build again
seem problem solved
strange
anyway...thanks @zho

**Comment by zho** [comment]
you're welcome... haha... sorry i was busy...
